//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaScaffoldFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int ID_CLI { get; set; }
        public Nullable<int> ID_SEC { get; set; }
        public string NOME_CLI { get; set; }
        public string CARGO { get; set; }
        public Nullable<int> PORTARIA { get; set; }
    }
}
