//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaScaffoldFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public int ID_EMPRESA { get; set; }
        public string NOME_EMPRESA { get; set; }
        public string ENDERECO_EMPRESA { get; set; }
        public string BAIRRO_EMPRESA { get; set; }
        public string CIDADE_EMPRESA { get; set; }
        public string UF_EMPRESA { get; set; }
        public string CEP_EMPRESA { get; set; }
        public string CNPJ_EMPRESA { get; set; }
        public string FONE_EMRESA { get; set; }
        public byte[] LOGO_EMPRESA { get; set; }
    }
}
