//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaScaffoldFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        public int ID_PRO { get; set; }
        public int ID_CLAS { get; set; }
        public int ID_UN_MED { get; set; }
        public string DESCRICAO { get; set; }
        public string OBSERVACAO { get; set; }
        public Nullable<int> ESTOQUE_MIN { get; set; }
        public Nullable<bool> PERECIVEL { get; set; }
        public Nullable<int> QTD_EMBALAGEM { get; set; }
    }
}
