//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaScaffoldFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECRETARIA
    {
        public int ID_SEC { get; set; }
        public string NOME_SEC { get; set; }
        public string ENDRECO_SEC { get; set; }
        public string BAIRRO_SEC { get; set; }
        public string EMAIL { get; set; }
        public string TEL { get; set; }
    }
}
