//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaScaffoldFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTEMAS
    {
        public string SISID { get; set; }
        public string SISDESCRICAO { get; set; }
        public string SISCHAVE { get; set; }
        public string DA { get; set; }
        public string DU { get; set; }
    }
}
