//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaScaffoldFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDADE_MEDIDA
    {
        public int ID_UN_MED { get; set; }
        public string NOME_UN_MED { get; set; }
        public string SIGLA { get; set; }
    }
}
